In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v1')

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

In [4]:
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
            
        # Update QQ-table for Q(s,a)
        q_table[state, action] = (1 - learning_rate) * q_table[state, action] + learning_rate * (reward+ discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)

    rewards_all_episodes.append(rewards_current_episode)

Calculate and pring the average reward per thousand episodes

In [7]:
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), num_episodes / 1000)
count = 1000
print('********Average reward per thousand episodes********\n')
for r in rewards_per_thousand_episodes:
    print(count, ': ', str(sum(r / 1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.03100000000000002
2000 :  0.19100000000000014
3000 :  0.44100000000000034
4000 :  0.5470000000000004
5000 :  0.6390000000000005
6000 :  0.6830000000000005
7000 :  0.6800000000000005
8000 :  0.6740000000000005
9000 :  0.6290000000000004
10000 :  0.6720000000000005


Print updated Q-table

In [8]:
print('\n\n********Q-table********\n')
print(q_table)



********Q-table********

[[0.52100731 0.50148114 0.48223781 0.50542312]
 [0.3466343  0.28782295 0.34563119 0.49393053]
 [0.40927455 0.40607999 0.38842632 0.47972268]
 [0.28316652 0.27303131 0.34497901 0.4637897 ]
 [0.54275435 0.42667944 0.40124616 0.22419624]
 [0.         0.         0.         0.        ]
 [0.34649625 0.15197467 0.22019754 0.16077449]
 [0.         0.         0.         0.        ]
 [0.40410224 0.46668781 0.34679384 0.59220775]
 [0.44802875 0.67541314 0.52256269 0.37440807]
 [0.69945433 0.48945495 0.30181178 0.32526991]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.47730479 0.5813678  0.7588177  0.491607  ]
 [0.71383227 0.87307961 0.73125936 0.70684397]
 [0.         0.         0.         0.        ]]


In [9]:
for episode in range(3):
    state = env.reset()
    done = False
    print('*****EPISODE ', episode + 1, '*****\n\n\n\n')
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print('****You reached the goal!****')
            else:
                print('****You fell through a hole!****')
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
